name: Github-Pages Build on Push
on:
    push:
        branches:
            - asozial

jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-

            - name: Download files
              run: |
                  curl https://raw.githubusercontent.com/asozialesnetzwerk/chat-configs/main/config.json > config.json
                  curl https://raw.githubusercontent.com/asozialesnetzwerk/chat-configs/main/customize.sh > customize.sh
                  chmod +x customize.sh

            - name: Build with yarn
              run: |
                  yarn install
                  RIOT_OG_IMAGE_URL="WebsiteIcon.svg" yarn build

            - name: Customize login page
              run: ./customize.sh

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: webapp
